/*
eslint no-console: ["error", { allow: ["warn", "error", "log"] }] */
import React from "react";
import getProperties from "fusion:properties";

/**
 * AddToCart functional component renders a paragraph and a button which on click invokes the addToCart function
 
 * @function addToCart
 * Calls the getProperties method imported from the fusion:properties namespace
 * getProperties returns the props stored inside the properties/index.json, which we deconstruct and assign to the apiOrigin constant
 * window.Sales.apiOrigin is set to the apiOrigin constant
 * calls the @async window.Sales.addItemToCart
 * @param {sku: string, priceCode: string, quantity: number}
 * @returns {Promise} Promise <APIErrorResponse | Cart>
 * */

function addToCart() {
  /*
    In this case we reset the apiOrigin to a reacheable one
    The apiOrigin is saved in the 'index.json' file inside the 'properties' folder
  */
  const { apiOrigin } = getProperties();
  window.Sales.apiOrigin = apiOrigin;
  /*
    the following is based of the doc instruction of use of the arc-sub's Sales/sdk api calls
    addItemToCart(sku: string, priceCode: string, quantity: number): Promise<APIErrorResponse | Cart>
    more can be found at: https://s3.amazonaws.com/arc-learning-center-static/docs/api/arc-sdks/modules/sdk_sales.html#additemtocart
    In this case it will return and error, with a code generated by the SDK, due to the lack of authentication
  */
  window.Sales.addItemToCart("test", "test", 1)
    .then(console.log)
    .catch(console.error);
  /*
    REPLACE THE ABOVE CONSOLE STATEMENTS WITH THE APPROPRIATE LOGIC ONCE YOU START DEVELOPMENT
    */
}

const AddToCart = () => {
  return (
    <div className="container">
      <p className="font--primary">
        The below button makes a call to the arc-subs Sales/SDK and logs the
        response
      </p>
      <button
        className="btn btn--secondary font--primary"
        onClick={() => {
          addToCart();
        }}
      >
        Add to Cart
      </button>
    </div>
  );
};

export default AddToCart;
